# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages
RUN npm install

# Copy the backend code (App.js) to the working directory
COPY App.js ./

# Start the Node.js application
CMD ["node", "App.js"]

# Expose port 4000
EXPOSE 4000
